version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    env_file:
      - .env
    command: bash -c "npm run prisma:generate && npx prisma migrate dev && npm run seed && npm start"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 070975
    
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
